#!/bin/sh
set -e

echo "Encrypting vault files before commit..."
make encrypt-vault

# Re-stage uniquement le vault chiffré (et pas les autres fichiers en cours)
git add group_vars/portfolio_group/vault.yml

echo "Re-decrypting vault files after commit..."
make decrypt-vault

exit 0