---
collections:
  - name: community.general
    version: "==12.6.0"
  - name: community.docker
    version: "==5.2.0"
  - name: ansible.posix
    version: "==2.1.0"
  - name: jyok1m.docker_compose
    version: "==2.0.1"
  - name: jyok1m.hardening
    version: "==1.1.0"
  - name: jyok1m.k3s
    version: "==1.0.1"
  - name: jyok1m.backups
    version: "==1.0.0"
  # - source: ./collections/k3s
  #   type: dir
