---
- name: Prepare hosts for ssh / firewall hardening and vRack configuration
  hosts: all
  roles:
    - { role: hardening, tags: [hardening] }
    - { role: vRack, tags: [vRack] }
  tags: [setup]

- name: Install engines and runtimes
  hosts: all
  roles:
    - { role: docker, tags: [docker] }
  tags: [engines]

- name: Install common apps
  hosts: all
  roles:
    - { role: traefik, tags: [traefik] }
    - { role: jenkins, tags: [jenkins] }
    - { role: monitoring, tags: [monitoring] }
  tags: [common]

- name: Install client apps
  hosts: all
  roles:
    - { role: portfolio, tags: [portfolio] }
    - { role: ipseis, tags: [ipseis] }
  tags: [client]

- name: Install private apps
  hosts: all
  roles:
    - { role: mongo_test, tags: [mongo_test] }
    - { role: n8n, tags: [n8n] }
  tags: [private]
