---
- name: Apply ssh hardening
  ansible.builtin.import_role:
    name: jyok1m.hardening.ssh_hardening
  vars:
    ssh_port: "{{ ovh_portfolio_port }}"
    ssh_allowed_users: ["{{ ovh_portfolio_user }}", "jenkins"]

- name: Apply firewall hardening
  ansible.builtin.import_role:
    name: jyok1m.hardening.firewall
  vars:
    ufw_allowed_ports:
      - { port: "{{ ovh_portfolio_port }}", proto: tcp, comment: SSH }
      - { port: 80, proto: tcp, comment: HTTP }
      - { port: 443, proto: tcp, comment: HTTPS }

- name: Apply fail2ban hardening
  ansible.builtin.import_role:
    name: jyok1m.hardening.fail2ban
  vars:
    fail2ban_ssh_port: "{{ ovh_portfolio_port }}"
