---
ufw_allowed_ports:
  - port: "{{ vault_ovh_portfolio_port }}"
    proto: "tcp"
    comment: "SSH"
  - port: "80"
    proto: "tcp"
    comment: "HTTP"
  - port: "443"
    proto: "tcp"
    comment: "HTTPS"
