---
driver:
  name: docker
platforms:
  - name: swarm-test-manager
    image: geerlingguy/docker-debian13-ansible:latest
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    networks:
      - name: molecule-swarm-net
    groups:
      - swarm_managers
  - name: swarm-test-worker
    image: geerlingguy/docker-debian13-ansible:latest
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    networks:
      - name: molecule-swarm-net
    groups:
      - swarm_workers
provisioner:
  name: ansible
  env:
    ANSIBLE_DEPRECATION_WARNINGS: "False"
verifier:
  name: ansible
