---
- name: Deploy {{ app_name }}
  ansible.builtin.import_role:
    name: jyok1m.docker_compose.deploy
  vars:
    docker_compose_app_name: "{{ app_name }}"
    docker_compose_app_path: "{{ app_path }}"
    docker_compose_templates:
      - src: docker-compose.yml.j2
        dest: docker-compose.yml
        no_log: true

- name: Deploy {{ app_name_dev }}
  ansible.builtin.import_role:
    name: jyok1m.docker_compose.deploy
  vars:
    docker_compose_app_name: "{{ app_name_dev }}"
    docker_compose_app_path: "{{ app_path }}"
    docker_compose_templates:
      - src: docker-compose.dev.yml.j2
        dest: docker-compose.dev.yml
        no_log: true

- name: Schedule {{ app_name }}-db dumps
  ansible.builtin.import_role:
    name: jyok1m.backups.mongo_dump
  vars:
    mongo_dump_name: "{{ app_name }}"
    mongo_dump_container: "{{ app_name }}-db"
    mongo_dump_network: "{{ app_name }}-internal"
    mongo_dump_username: "{{ vault_ipseis_db_root_user }}"
    mongo_dump_password: "{{ vault_ipseis_db_root_password }}"
    mongo_dump_restic_repo: "s3:https://s3.gra.io.cloud.ovh.net/{{ app_name }}"
    mongo_dump_restic_password: "{{ vault_restic_password_portfolio }}"
    mongo_dump_restic_env:
      AWS_ACCESS_KEY_ID: "{{ vault_ovh_s3_access_key_portfolio }}"
      AWS_SECRET_ACCESS_KEY: "{{ vault_ovh_s3_secret_key_portfolio }}"
    mongo_dump_on_calendar: "*-*-* 03:00:00"

- name: Install {{ app_name }} restore tooling
  ansible.builtin.import_role:
    name: jyok1m.backups.mongo_restore
  vars:
    mongo_restore_name: "{{ app_name }}"
    mongo_restore_username: "{{ vault_ipseis_db_root_user }}"
    mongo_restore_password: "{{ vault_ipseis_db_root_password }}"
    mongo_restore_restic_repo: "s3:https://s3.gra.io.cloud.ovh.net/{{ app_name }}"
    mongo_restore_restic_password: "{{ vault_restic_password_portfolio }}"
    mongo_restore_restic_env:
      AWS_ACCESS_KEY_ID: "{{ vault_ovh_s3_access_key_portfolio }}"
      AWS_SECRET_ACCESS_KEY: "{{ vault_ovh_s3_secret_key_portfolio }}"
