---
- name: Check if Docker is already installed
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: docker_binary

- name: Download Docker install script
  ansible.builtin.get_url:
    url: "{{ docker_install_script_url }}"
    dest: /tmp/get-docker.sh
    mode: "0755"
  when: not docker_binary.stat.exists

- name: Run Docker install script
  ansible.builtin.command: sh /tmp/get-docker.sh
  when: not docker_binary.stat.exists
  changed_when: true

- name: Add ansible_user to the docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Ensure Docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Remove Docker install script
  ansible.builtin.file:
    path: /tmp/get-docker.sh
    state: absent
  when: not docker_binary.stat.exists

- name: Login to Docker Hub
  community.docker.docker_login:
    registry_url: "{{ docker_registry_url }}"
    username: "{{ docker_username }}"
    password: "{{ docker_token }}"
