---
- name: Install Docker and authenticate against Docker Hub
  ansible.builtin.import_role:
    name: jyok1m.docker_compose.install
  vars:
    docker_install_users:
      - "{{ ansible_user }}"
    docker_install_login: true
    docker_install_username: "{{ vault_dockerhub_username }}"
    docker_install_password: "{{ vault_dockerhub_token }}"
