---
- name: Nettoyage du symlink cloud-init
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d/50-cloud-init.conf
    state: absent # Supprimer le fichier de configuration généré par cloud-init
  notify: Redémarrage de sshd

- name: Application du template de configuration ssh
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
    backup: yes # avec backup (OKAZOU)
  notify: Redémarrage de sshd
